spring:
  application:
    name: student-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://mariadb-service:30028/testdb
  #    username: beyond
  #    password: beyond
  #    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5  # 이 값이 연결 풀 크기

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate: DEBUG