spring:
  application:
    name: notification-service

  datasource:
#    url: jdbc:mariadb://121.170.161.72:30028/testdb
#    username: beyond
#    password: beyond
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-service/testdb
    username: beyond
    password: beyond
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate: DEBUG
