apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-label
  template:
    metadata:
      labels:
        app: auth-label
    spec:
      containers:
      - name: auth
        image: jjjwww8802/auth-service:1.0
        ports:
        - containerPort: 9000
