apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calendar-label
  template:
    metadata:
      labels:
        app: calendar-label
    spec:
      containers:
      - name: calendar
        image: jjjwww8802/calendar-service:1.0
        ports:
        - containerPort: 8080