apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calendar-label
  template:
    metadata:
      labels:
        app: calendar-label
    spec:
      containers:
      - name: calendar
        image: calendar-service:7.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"