apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-label
  template:
    metadata:
      labels:
        app: notification-label
    spec:
      containers:
      - name: notification
        image: jjjwww8802/notification-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
