apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notice-label
  template:
    metadata:
      labels:
        app: notice-label
    spec:
      containers:
      - name: notice
        image: notice-service:1.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"