apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-label
  template:
    metadata:
      labels:
        app: notification-label
    spec:
      containers:
      - name: notification
        image: jjjwww8802/notification-service:1.0
        ports:
        - containerPort: 9000