apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notice-label
  template:
    metadata:
      labels:
        app: notice-label
    spec:
      containers:
      - name: notice
        image: jjjwww8802/notice-service:1.0
        ports:
        - containerPort: 9000