apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notice-label
  template:
    metadata:
      labels:
        app: notice-label
    spec:
      containers:
      - name: notice
        image: notice-service:1.0
        resources:
          # 최소 사양
          requests:
            memory: "128Mi"
            cpu: "500m"
          # 최대 사양
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 9000