apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-label
  template:
    metadata:
      labels:
        app: student-label
    spec:
      containers:
      - name: student
        image: jjjwww8802/student-service:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2"