apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-label
  template:
    metadata:
      labels:
        app: student-label
    spec:
      containers:
      - name: student
        image: student-service:1.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"